import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const az = {
  translation: {
    home: 'Ana səhifə', listings: 'Elanlar', categories: 'Kateqoriyalar', favorites: 'Favorilər', login: 'Daxil ol', search: 'Axtar', searchPlaceholder: 'Nə axtarırsınız?', negotiable: 'Razılaşma yolu ilə', heroKicker: 'Al, sat, rahat tap', heroTitle: 'Azərbaycanda al və sat', heroText: 'İstədiyiniz məhsulu tapın, elanınızı saniyələr içində yerləşdirin.', popularCategories: 'Populyar kateqoriyalar', browseAds: 'Elanlara bax', latest: 'Ən son elanlar', viewAll: 'Hamısına bax', why: 'Niyə TAPAR.AZ?', trustTitle: 'Axtardığını tap, güvənlə al', trust1: 'Daha güvənli alış-veriş', trust2: 'Axtardığınızı tez tapın', trust3: 'Aktiv alıcı icması', details: 'Ətraflı bax', noImage: 'Şəkil yoxdur', added: 'Yerləşdirilib', rating: 'rəy', viewers: 'baxış', city: 'Şəhər', category: 'Kateqoriya', subcategory: 'Alt kateqoriya', priceRange: 'Qiymət aralığı (AZN)', allCategories: 'Bütün kateqoriyalar', allSubcategories: 'Bütün alt kateqoriyalar', allCities: 'Bütün şəhərlər', filters: 'Filtrlər', allListings: 'Bütün elanlar', shown: 'elan göstərilir', noResults: 'Bu filtrlərə uyğun elan tapılmadı', newest: 'Əvvəlcə yeni', cheapest: 'Ucuzdan bahaya', expensive: 'Bahadan ucağa', mostViewed: 'Ən çox baxılan', topRated: 'Ən yüksək reytinq', seller: 'Elan sahibi', showPhone: 'Telefonu göstər', backToAd: 'Elana qayıt', trustText1: 'Telefonu təsdiqlənmiş satıcıları asanlıqla tanıyın.', trustText2: 'Ağıllı filterlər və kateqoriyalarla vaxtınıza qənaət edin.', trustText3: 'Elanınızı minlərlə potensial alıcıya göstərin.', 'category.daşınmaz_əmlak': 'Daşınmaz Əmlak', 'category.iş_elanları': 'İş Elanları', 'category.xidmətlər': 'Xidmətlər', 'category.elektronika': 'Elektronika', 'category.ev_bağ': 'Ev və Bağ',
  },
};

const en = { translation: { ...az.translation, home: 'Home', listings: 'Listings', categories: 'Categories', favorites: 'Favorites', login: 'Log in', search: 'Search', searchPlaceholder: 'What are you looking for?', details: 'View details', noImage: 'No image', added: 'Posted', rating: 'reviews', viewers: 'views', city: 'City', category: 'Category', subcategory: 'Subcategory', seller: 'Seller', showPhone: 'Show phone', backToAd: 'Back to listing' } };
const ru = { translation: { ...az.translation, home: 'Главная', listings: 'Объявления', categories: 'Категории', favorites: 'Избранное', login: 'Войти', search: 'Поиск', searchPlaceholder: 'Что вы ищете?', details: 'Подробнее', noImage: 'Нет изображения', added: 'Размещено', rating: 'отзывов', viewers: 'просмотров', city: 'Город', category: 'Категория', subcategory: 'Подкатегория', seller: 'Продавец', showPhone: 'Показать телефон', backToAd: 'Вернуться к объявлению' } };

i18n.use(initReactI18next).init({ resources: { az, en, ru }, lng: 'az', fallbackLng: 'az', interpolation: { escapeValue: false } });
export default i18n;
