import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const az = {
  translation: {
    home: 'Ana səhifə', listings: 'Elanlar', cars: 'Avtomobillər', categories: 'Kateqoriyalar', favorites: 'Favorilər', aiListing: 'AI Elan', login: 'Daxil ol', messages: 'Mesajlar', placeAd: 'Elan yerləşdir', search: 'Axtar', searchPlaceholder: 'Nə axtarırsınız?', negotiable: 'Razılaşma yolu ilə', heroKicker: 'Al, sat, rahat tap', heroTitle: 'Azərbaycanda al və sat', heroText: 'İstədiyiniz məhsulu tapın, elanınızı saniyələr içində yerləşdirin.', popularCategories: 'Populyar kateqoriyalar', browseAds: 'Elanlara bax', latest: 'Ən son elanlar', popularCars: 'Populyar avtomobillər', viewAll: 'Hamısına bax', why: 'Niyə TAPAR.AZ?', trustTitle: 'Axtardığını tap, güvənlə al', trust1: 'Daha güvənli alış-veriş', trust2: 'Axtardığınızı tez tapın', trust3: 'Aktiv alıcı icması', sellEasy: 'Satışa başlamaq çox asandır', details: 'Ətraflı bax', noImage: 'Şəkil yoxdur', added: 'Yerləşdirilib', rating: 'rəy', viewers: 'baxış', city: 'Şəhər', category: 'Kateqoriya', subcategory: 'Alt kateqoriya', priceRange: 'Qiymət aralığı (AZN)', allCategories: 'Bütün kateqoriyalar', allSubcategories: 'Bütün alt kateqoriyalar', allCities: 'Bütün şəhərlər', filters: 'Filtrlər', allListings: 'Bütün elanlar', shown: 'elan göstərilir', noResults: 'Bu filtrlərə uyğun elan tapılmadı', newest: 'Əvvəlcə yeni', cheapest: 'Ucuzdan bahaya', expensive: 'Bahadan ucuza', mostViewed: 'Ən çox baxılan', topRated: 'Ən yüksək reytinq', seller: 'Elan sahibi', showPhone: 'Telefonu göstər', messageSeller: 'Satıcıya mesaj yaz', noMessages: 'Hələ mesajınız yoxdur', newMessages: 'yeni', send: 'Göndər', writeMessage: 'Mesajınızı yazın...', backToAd: 'Elana qayıt', trustText1: 'Telefonu təsdiqlənmiş satıcıları asanlıqla tanıyın.', trustText2: 'Ağıllı filterlər və kateqoriyalarla vaxtınıza qənaət edin.', trustText3: 'Elanınızı minlərlə potensial alıcıya göstərin.', 'category.avtomobiller': 'Avtomobillər', 'category.daşınmaz_əmlak': 'Daşınmaz Əmlak', 'category.iş_elanları': 'İş Elanları', 'category.xidmətlər': 'Xidmətlər', 'category.elektronika': 'Elektronika', 'category.ev_bağ': 'Ev və Bağ',
  },
};

const en = { translation: {
  home: 'Home', listings: 'Listings', cars: 'Cars', categories: 'Categories', favorites: 'Favorites', aiListing: 'AI Listing', login: 'Log in', messages: 'Messages', placeAd: 'Post an ad', search: 'Search', searchPlaceholder: 'What are you looking for?', negotiable: 'Negotiable', heroKicker: 'Buy, sell, find it easily', heroTitle: 'Buy and sell in Azerbaijan', heroText: 'Find what you need and post your listing in seconds.', popularCategories: 'Popular categories', browseAds: 'Browse listings', latest: 'Latest listings', popularCars: 'Popular cars', viewAll: 'View all', why: 'Why TAPAR.AZ?', trustTitle: 'Find what you need, buy with confidence', trust1: 'Safer shopping', trust2: 'Find it faster', trust3: 'An active buyer community', sellEasy: 'Selling starts here', details: 'View details', noImage: 'No image', added: 'Posted', rating: 'reviews', viewers: 'views', city: 'City', category: 'Category', subcategory: 'Subcategory', priceRange: 'Price range (AZN)', allCategories: 'All categories', allSubcategories: 'All subcategories', allCities: 'All cities', filters: 'Filters', allListings: 'All listings', shown: 'listings shown', noResults: 'No listings match these filters', newest: 'Newest first', cheapest: 'Lowest price', expensive: 'Highest price', mostViewed: 'Most viewed', topRated: 'Top rated', seller: 'Seller', showPhone: 'Show phone', messageSeller: 'Message seller', noMessages: 'No messages yet', newMessages: 'new', send: 'Send', writeMessage: 'Write your message...', backToAd: 'Back to listing', trustText1: 'Identify phone-verified sellers with confidence.', trustText2: 'Save time with smart filters and categories.', trustText3: 'Reach thousands of potential buyers.', 'category.avtomobiller': 'Cars', 'category.daşınmaz_əmlak': 'Real estate', 'category.iş_elanları': 'Jobs', 'category.xidmətlər': 'Services', 'category.elektronika': 'Electronics', 'category.ev_bağ': 'Home & Garden',
} };

const ru = { translation: {
  home: 'Главная', listings: 'Объявления', cars: 'Автомобили', categories: 'Категории', favorites: 'Избранное', aiListing: 'AI объявление', login: 'Войти', messages: 'Сообщения', placeAd: 'Подать объявление', search: 'Поиск', searchPlaceholder: 'Что вы ищете?', negotiable: 'Договорная', heroKicker: 'Покупай, продавай, находи легко', heroTitle: 'Покупайте и продавайте в Азербайджане', heroText: 'Находите нужное и размещайте объявление за считанные секунды.', popularCategories: 'Популярные категории', browseAds: 'Смотреть объявления', latest: 'Новые объявления', popularCars: 'Популярные автомобили', viewAll: 'Смотреть все', why: 'Почему TAPAR.AZ?', trustTitle: 'Находите нужное и покупайте уверенно', trust1: 'Безопасные покупки', trust2: 'Быстрый поиск', trust3: 'Активное сообщество покупателей', sellEasy: 'Начать продажу очень просто', details: 'Подробнее', noImage: 'Нет изображения', added: 'Размещено', rating: 'отзывов', viewers: 'просмотров', city: 'Город', category: 'Категория', subcategory: 'Подкатегория', priceRange: 'Диапазон цены (AZN)', allCategories: 'Все категории', allSubcategories: 'Все подкатегории', allCities: 'Все города', filters: 'Фильтры', allListings: 'Все объявления', shown: 'объявлений показано', noResults: 'По этим фильтрам объявлений нет', newest: 'Сначала новые', cheapest: 'Сначала дешевые', expensive: 'Сначала дорогие', mostViewed: 'Больше просмотров', topRated: 'Высокий рейтинг', seller: 'Продавец', showPhone: 'Показать телефон', messageSeller: 'Написать продавцу', noMessages: 'Сообщений пока нет', newMessages: 'новых', send: 'Отправить', writeMessage: 'Напишите сообщение...', backToAd: 'Вернуться к объявлению', trustText1: 'Легко находите продавцов с подтвержденным телефоном.', trustText2: 'Экономьте время с умными фильтрами и категориями.', trustText3: 'Покажите объявление тысячам потенциальных покупателей.', 'category.avtomobiller': 'Автомобили', 'category.daşınmaz_əmlak': 'Недвижимость', 'category.iş_elanları': 'Работа', 'category.xidmətlər': 'Услуги', 'category.elektronika': 'Электроника', 'category.ev_bağ': 'Дом и сад',
} };

i18n.use(initReactI18next).init({ resources: { az, en, ru }, lng: 'az', fallbackLng: 'az', interpolation: { escapeValue: false } });
export default i18n;
